# .github/workflows/cicd.yml

name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          cache-from: type=inline
          cache-to: type=inline

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          cache-from: type=inline
          cache-to: type=inline

      # ---- NEW STEP TO CREATE .ENV FILE ----
      - name: Create .env file for Backend
        run: |
          echo "Creating .env file..."
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo ".env file created successfully."

      - name: Deploy to EC2 with Docker Compose
        run: |
          echo "Pulling latest images..."
          docker-compose pull
          
          echo "Stopping and removing old containers, and starting new ones..."
          docker-compose up -d --force-recreate
          
          echo "Cleaning up dangling images..."
          docker image prune -f